# Generated by Django 2.2.4 on 2024-05-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20240518_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='teams',
            new_name='team',
        ),
    ]
